reading_task:
  description: >
    Extract the entire text from the PDF document at C:\Users\Ricardo Amorim\IdeaProjects\sample_data\david_matos.pdf
    Return the raw text content without modification
  expected_output: >
    The complete extracted text of the PDF Document.
  agent: pdf_reader

summarizing_task:
  description: >
    Take the provided PDF text and summarize it into a concise overview that highlighst the main points.
  expected_output: >
    A consice summary (around 2-4 paragraph) highlighting the key themes and facts from the document.
  agent: summarizer
  context: 
    - reading_task
  output_file: summary.md